### ISSUE TITLE
Lazy evaluation?

### ISSUE THREAD

**Issue by winthropchang** [ImLiam/Lua-Collections#5]
Is your calculation is Lazy evaluation?
collect({1, 2, 3, 4}):filter(function(key, value)
    return value > 2
end)
:map(function(key, value ){
    return key, value * 2
})
:all();
Collection will filter all elements then map?
Or filter each element and map?

**Comment by imliam** [comment]
It will filter all elements then map the result afterwards, each chain is done in turn for the whole collection.
